spring:
  server:
    port: 8080
  application:
    name: rest-spring-boot-dev
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # Hikari specific configurations
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000        # 5 minutes
      max-lifetime: 1200000       # 20 minutes
      connection-timeout: 20000   # 20 seconds
      pool-name: H2HikariCP
      auto-commit: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Spring Boot REST API
    version: 1.0.0
    java:
      version: ${java.version}
